### ISSUE TITLE
[Enhancement] Adding a yMax and yMin flag

### ISSUE THREAD

**Issue by TagCraftMC** [Phoenix616/RandomTeleport#1]
Hi Phoenix616,

We we're wondering if you're able to implement a yMax and yMin flag. 
The software works great, however there are times that the player TP's to "out of reach" places, being able to set the max and min levels they can teleport to would be wonderful.

Thanks for your time and great plugin.

**Comment by Phoenix616** [comment]
These flags are already on my todo list for the plugin and I will implement them if I come up with a good solution. It currently only uses the Bukkit API's method and no own algorithm.

**Comment by Phoenix616** [comment]
Also implemented with 081d21705302c0b8b82965cbfeec69f5fbfda93a
