### ISSUE TITLE
Add a possibility/file (language.yml) 

### ISSUE THREAD

**Issue by GamerOfEnder** [Phoenix616/RandomTeleport#16]
Hey ! Can you please add a file (language.yml)/possibility (in config.yml) to translate all broadcast messages ? thanks for the answer :)

**Comment by Phoenix616** [comment]
Please provide some information on the messages that you are missing as the config already contains [a messages section](https://github.com/Phoenix616/RandomTeleport/blob/master/RandomTeleport%20v1.0/src/main/resources/config.yml#L11-L17)?

**Comment by Phoenix616** [comment]
Will be added in the 2.0 rewrite once #23 is resolved.
