### ISSUE TITLE
Server hangs when filtering for Biomes

### ISSUE THREAD

**Issue by NolanMC** [Phoenix616/RandomTeleport#21]
Paper Version: 214 - 1.13.1
Random Teleport: Latest Build
Command executed: rtp 1000 50000 -c 120 -b PLAINS -w world
Error: https://paste.md-5.net/volojirexu.vbs

I assume this is because of how chunks currently only loads chunks on the main thread. In case that is not true, I figure that I should report this hanging and see if anything can be done about it. I have been able to reproduce this without fail multiple times under these pretenses. 

Alternative: Support for the upcoming Async Chunk Loading Branch of Paper to avoid hanging on chunk loads (if that is in fact the issue).
Error when using this branch: https://paste.md-5.net/vunidiwati.avrasm
Location of this branch of Paper: : https://github.com/PaperMC/Paper/tree/async-chunks

Thanks in advance, love the plugin!

**Comment by Phoenix616** [comment]
Well yeah, the speed, especially with such a large radius is highly depended on the speed of the chunk loads. (for now you could only teleport to loaded chunks I guess) I have some ideas for improving that directly in the plugin but these wont be put into it before the rewrite.

Also regarding paper's async loading: If they decide to load them differently than the normal server (or how it used to work pre 1.13 then it should be done in a way that doesn't break existing plugins using the normal API. If they decide to offer a better way of getting chunk contents async in a separate thread then I will add compatibility for that, but if it's implemented in a way that breaks existing plugins then it's hard to fix that without breaking compatibility for everyone else.

**Comment by Phoenix616** [comment]
Should be working now in v2.
