### ISSUE TITLE
Improve message config system

### ISSUE THREAD

**Issue by Phoenix616** [Phoenix616/RandomTeleport#23]
Currently it is not possible to completely disable certain messages or to configure certain message types (like permission denied messages)

**Comment by Phoenix616** [comment]
Should probably use [Phoenix616/lang](https://github.com/Phoenix616/lang)

**Comment by Heliosard** [comment]
HLang is public? I do not agree with that.

**Comment by Phoenix616** [comment]
Now uses a language system which has the ability for multiple, per player languages and no hardcoded messages.
