### ISSUE TITLE
Error in save-blocks config!

### ISSUE THREAD

**Issue by FatherWh0** [Phoenix616/RandomTeleport#31]
When loading FUBS Random Teleport with paper 1.14.2 the following series of errors occur:
https://pastebin.com/Mm3rLxma
RandomTP: Jenkins build # 46

**Comment by Phoenix616** [comment]
The default config currently contains the block names for 1.12.2, if you
want to use a version above that you'll have to update that with the new
block names.

**Comment by FatherWh0** [comment]
I'm sry but I'm confused. The config file doesn't have any block names in it.
https://pastebin.com/f23APSrb

**Comment by Phoenix616** [comment]
Please take a look at the [config of the new version](https://github.com/Phoenix616/RandomTeleport/blob/master/randomteleport-plugin/src/main/resources/config.yml) and adjust yours accordingly.

**Comment by FatherWh0** [comment]
Thank you.
