### ISSUE TITLE
Cooldown not working

### ISSUE THREAD

**Issue by Dinoosawruss** [Phoenix616/RandomTeleport#32]
Can't get cooldown to work
default: "100 5000 -f -x 0 -z 0 -w world -cooldown 2700 -f"

**Comment by Phoenix616** [comment]
Can you please provide the server and plugin version that you are trying to use that as well as how you run the command.

**Comment by Dinoosawruss** [comment]
Server - 1.13.2 Paper
Plugin - Latest
Running command with just /rtp

**Comment by Phoenix616** [comment]
Please provide the actual output of the /version command for bot the server and the plugin.

**Comment by Dinoosawruss** [comment]
![image](https://user-images.githubusercontent.com/22278485/61893341-c36e6500-af05-11e9-9db8-6a74ff0ca4bb.png)

**Comment by Dinoosawruss** [comment]
OH and 1.7.4 for plugin

**Comment by Phoenix616** [comment]
1.7.4 is not the latest plugin version. Please update to the latest v2 development build and see if the issue persists.

**Comment by Dinoosawruss** [comment]
Updated, still not working. The RTP works fine but there is no cooldown

**Comment by Phoenix616** [comment]
Are you sure that you don't just have the `randomteleport.cooldownexempt` permission? (Granted to OPs by default)

**Comment by Dinoosawruss** [comment]
No, I've tested it with players not myself

**Comment by Dinoosawruss** [comment]
![image](https://user-images.githubusercontent.com/22278485/61897094-3da2e780-af0e-11e9-8814-981c2cd8e036.png)

**Comment by Dinoosawruss** [comment]
Still not working? Hello?

**Comment by Phoenix616** [comment]
It is working when I test it. Please provide more information about how you are using it as well as your full config and log file. (And ideally the full permission setup e.g. via LuckPerm's tree view or editor)

**Comment by Dinoosawruss** [comment]
Sorry, but I don’t understand what I have to do to fix based on the edit? Just update to the latest build or?

**Comment by Phoenix616** [comment]
Yes, just update to the latest build.

**Comment by Dinoosawruss** [comment]
Uhh, I've updated to the latest build and now /rtp does nothing except send this to console:
[RandomTeleport] Running preset command default: 100 5000 -f -x 0 -z 0 -w world -cooldown 2700 -f -p Premiership

**Comment by Phoenix616** [comment]
That message is nowhere in the plugin and it shouldn't print a message to the console (unless the console runs the command I guess). Please provide your log file, config and specific plugin version that you are using.

**Comment by Dinoosawruss** [comment]
I’m on holiday now, I’ve asked Tonus (who is another owner) to deal with the issue

**Comment by masonzettle** [comment]
Hello, this is Tonus.
We were running build #49, but that didn't work at all so Dino reverted to the previous version we were on (neither Dino or I know what that is).
Here's the config: [config.zip](https://github.com/Phoenix616/RandomTeleport/files/3448424/config.zip)
As for the log file, are you referring to latest.log? If so, what do we need to do on the server and what parts of the log file do you want?

**Comment by Phoenix616** [comment]
Ok the config looks normal. The full lastest.log file from a session when the plugin was used and didn't work properly would be the most helpful.

**Comment by Dinoosawruss** [comment]
Issue is apparently fixed. Have a nice day
