### ISSUE TITLE
Chunks do not Load on 1.16

### ISSUE THREAD

**Issue by Pemigrade** [Phoenix616/RandomTeleport#39]
Chunks do not load after a player /rtps with this plugin on 1.16, despite TPS being 20.0. They have to relog in order to load the chunks. I'm not sure if this is a problem with the plugin or with 1.16 as a whole.

**Comment by Phoenix616** [comment]
Can you please provide your exact server and plugin version as well as your server's log and the used command?

But it's very unlikely that it's an issue with the plugin itself, usually the server is responsible for loading chunks and 1.16 is far from done.

**Comment by Pemigrade** [comment]
I'm not quite sure what was happening, but the issue seems to have fixed itself. I was thinking it may have been because of this plugin since chunks still loaded when I did /to [random coordinates], but not rtp. It's possible I was using a buggy version of paper or something. Thanks for the help!
