### ISSUE TITLE
Inside lava

### ISSUE THREAD

**Issue by pintoso** [Phoenix616/RandomTeleport#44]
#### Plugin Version
Build #82
 
 
#### Config
default
 
#### Environment description
1.16.4 paper #404

#### What is happening?
I'm teleported inside the lava
commands used in the video:
```
/randomteleport:rtp 50 500 -x 0 -z 1000 -maxY 120 -w world_nether
/randomteleport:rtp 50 500 -x 0 -z 1000 -maxY 120 -w world_nether -f
/randomteleport:rtp 50 500 -x 0 -z 1000 -maxY 120 -w world_nether -f blocks
```

#### Additional context

https://user-images.githubusercontent.com/26844778/108662749-ba60c380-74ad-11eb-96cb-84784a4e0184.mp4

**Comment by Phoenix616** [comment]
Please provide your config file too (as that contains the blocks it should or shouldn't teleport into). Also in the video it looks like the lave is above you, not that it teleports inside the lava? Or is that just a visual quirk?

**Comment by pintoso** [comment]
I'm inside the lava in the video (I use a mod to see "better") 
config is the default ( [config.yml](https://paste.gg/p/anonymous/f81fae27fe554ec986a3a534c260e4de) )
>btw testing with other settings resulted in the same problem
