### ISSUE TITLE
[small idea] change default "-maxY" for nether to "126"

### ISSUE THREAD

**Issue by RedstoneFuture** [Phoenix616/RandomTeleport#50]
#### Is your feature request related to a problem? Please describe.
In my opinion, the default maxY are too high for the nether.

code line:
https://github.com/Phoenix616/RandomTeleport/blob/8e0643e59c89ff3841e8b7b7cc0b01bdecd324c5/randomteleport-plugin/src/main/java/de/themoep/randomteleport/searcher/RandomSearcher.java#L94

#### Describe the solution you'd like

I suggest a default value of maxY=126 for nether, because with 127 the plugin never find a save location, if you down't defined BEDROCK as safe block.

#### Describe alternatives you've considered
Currently, I use the command argument "-maxY 126" for my default preset. I'm fine with this, too.

**Comment by Phoenix616** [comment]
Thanks for the input on that, I don't really use it in the nether myself.

**Comment by johnfriedrich** [comment]
@Phoenix616 This change breaks support for 1.16 and lower as the api version in plugin.yml was raised

**Comment by Phoenix616** [comment]
@johnfriedrich yes, new features can only work on new versions. If you want to use in on an old server you are also going to have to use an old plugin version that is still compatible.

**Comment by johnfriedrich** [comment]
That api was introcuded in 1.16.5. Stumbled across this when using that on my 1.16 hybrid server

**Comment by Phoenix616** [comment]
I guess it could be adjusted to use 1.16.5 then if it was already present there.

I would imagine that it was added rather late though and the api-version can't really check for patch versions so that might result in some issues on previous 1.16 versions but I doubt anyone runs those.

**Comment by johnfriedrich** [comment]
Np. Only mentioned as 1.16.5 is quite common in (hybrid) modded atm
