### ISSUE TITLE
error - thermos 1.7.10 server

### ISSUE THREAD

**Issue by mat41997** [Phoenix616/RandomTeleport#9]
logs
http://pastebin.com/G3Ck2kb5

**Comment by Phoenix616** [comment]
```
Caused by: java.lang.NoSuchMethodError:
org.bukkit.World.getWorldBorder()Lorg/bukkit/WorldBorder;
```

The latest versions are not compatible with your old Minecraft version. You
have to use a version of my plugin from before the WorldBorder update.

**Comment by Phoenix616** [comment]
`Caused by: java.lang.NoSuchMethodError: org.bukkit.World.getWorldBorder()Lorg/bukkit/WorldBorder;`

The latest versions are not compatible with your old Minecraft version. You
have to use a version of my plugin from before the WorldBorder update.
